apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: rds-secret
  namespace: kubeflow
spec:
  provider: aws
  secretObjects:
    - secretName: mysql-secret
      type: Opaque
      data:
        - objectName: "user"
          key: username
        - objectName: "pass"
          key: password
  parameters:
    objects: |
      - objectName: "secret-rds-kubeflow-733u"
        objectType: "secretsmanager"
        jmesPath:
            - path: "username"
              objectAlias: "user"
            - path: "password"
              objectAlias: "pass"
