apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- ../../dev
- namespace.yaml

# NOTE: var name must be unique globally to allow composition of multiple kustomize
# packages. Therefore, we added prefix `kfp-dev-` to distinguish it from
# others.
    # ml-pipeline sa's metadata.namespace will be first transformed by namespace field in kustomization.yaml
    # so that we only need to change kustomization.yaml's namespace field for namespace customization.
vars:
- fieldref:
    fieldPath: metadata.namespace
  name: kfp-dev-namespace
  objref:
    apiVersion: v1
    kind: ServiceAccount
    name: ml-pipeline
configurations:
- params.yaml
